language: node_js

node_js:
  - "node"
  - "14"
  - "12"
  - "10"

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 50
